### ISSUE TITLE
Migrate setup.py to pyproject.toml

### ISSUE THREAD

**Issue by kairoaraujo** [OwnCA/ownca#72]
The Python Package is moving to a centralized `pyproject.toml`.

**Comment by KAUTH** [comment]
I can help with this

**Comment by kairoaraujo** [comment]
Thank you!

**Comment by KAUTH** [comment]
Uploading the PR in a bit.
Useful material used was:
- https://peps.python.org/pep-0517/
- https://peps.python.org/pep-0518/
- https://peps.python.org/pep-0621/
- https://packaging.python.org/en/latest/specifications/core-metadata/
- https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml
- https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
- https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

Other comments:
/tmp/build-env-p34ukyql/lib/python3.7/site-packages/setuptools/config/pyprojecttoml.py:104: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.

we can also check that our package description will render properly on PyPI with:
twine check dist/*
