### ISSUE TITLE
Fix onwca typo

### ISSUE THREAD

**Issue by KAUTH** [OwnCA/ownca#78]
In different parts of the code we come across the spelling ```onwca``` or ```Onwca``` instead of ```ownca``` and ```Ownca``` respectively.
Examples:
- https://github.com/OwnCA/ownca/blob/master/ownca/exceptions.py#L31
- https://github.com/OwnCA/ownca/blob/master/tests/unit/ownca/test_ownca.py#L56

This issue is to find all occurrences of this typo and resolve them.

**Comment by Lakshayainani** [comment]
@KAUTH Can I pick it ?

**Comment by Lakshayainani** [comment]
Made a PR for the same: https://github.com/OwnCA/ownca/pull/79
@KAUTH Please review.

**Comment by Lakshayainani** [comment]
@kairoaraujo This issue can also be closed as part of the PR https://github.com/OwnCA/ownca/pull/79
